name: tests

on:
  push:

jobs:
  run-phpstan:
    runs-on: ubuntu-latest
    name: run php stan for coding standard
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, pdo, pdo_sqlite
          coverage: xdebug
      - name: Checkout Codebase
        uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute PHP Stan
        run: ./vendor/bin/phpstan --memory-limit=255M

  run-tests:
    runs-on: ubuntu-latest
    name: run test and check coverage
    # needs: run-phpstan
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, pdo, pdo_sqlite
          coverage: xdebug
      - name: Checkout Codebase
        uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          XDEBUG_MODE: coverage
        run: php artisan test --coverage --min=50

